version: "3"

services:
  app:
    container_name: "j-tla-monadic"
    build: .
    environment:
      MONGO_URL: "MONGO_ATLAS_URL"
      MONGO_DBNAME: "TLA-DB"
      PORT: 4001
    ports: 
      - "4001:4001"
      - "4200:4200"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules #not rewrite
