version: "3"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb+srv://jrosales:NsEqQEViYXYVUa5k@tla-db-kjvdd.mongodb.net/test?retryWrites=true&w=majority"
      MONGO_DBNAME: "TLA-DB"
      PORT: 4001
    ports: 
      - "4001:4001"
      - "4200:4200"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules #not rewrite